name: "welcome"

on:
  push:
    branches:
      - new_branch
      - main
  pull_request: 
    branches: [main]

jobs:
  
  welcome:
    name: Print Welcome Message
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: print welcome message
        run: echo "Welcome user wyd?"
        
  build:
    name: Build App
    needs: welcome
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
        
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Test
        run: dotnet test
        
    
  publish:
    name: Publish App
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish
        run: dotnet publish